### ISSUE TITLE
Move nCine among the solo engines

### ISSUE THREAD

**Issue by encelo** [redorav/public_source_engines#4]
Thank you for adding the nCine in your list and thank you for listing it among the big team engines. 😄 
Unfortunately I have been the only developer of the project so you might want to move it among the solo ones. 😉

**Comment by redorav** [comment]
Hi @encelo, thanks for letting me know, I'll do that for sure. The reason I put it in the other category is the website is so nice and there's so much in there I thought there must be a lot of people working on it!

**Comment by redorav** [comment]
Closed via 764d4f507936bdd4540391e29ffcf771c1041208

I've also rephrased the definition a little as yours probably doesn't fall in the experimental or toy tech, to cover a bit more ground. Thanks again!
