### ISSUE TITLE
EquilibriumEngine

### ISSUE THREAD

**Issue by clibequilibrium** [redorav/public_source_engines#9]
Hi, great repo. 

You can add my ECS Game Engine written in C, powered by flecs and bgfx . 

Features shader and code hot-reloading, crash protection, forward & deferred shading, hot-reloading of imgui & entity inspector. Great entry code for beginners to learn data oriented pattern and get started with C in general. 

Thanks

https://github.com/clibequilibrium/EquilibriumEngine

**Comment by redorav** [comment]
Done, thank you!
